// Code generated by youdoyou-firestore-kit. DO NOT EDIT.

package schema

import (
	"time"
)

// Collection names
const (
	CollectionActivities = "activities"
)

// ActivityPath returns the document path for a activity.
func ActivityPath(activityID string) string {
	return "activities/" + activityID
}

type Activity struct {
	ID        string    `firestore:"-" json:"id" yaml:"id"`
	ProjectId string    `firestore:"projectId" json:"projectId" yaml:"projectId"`
	EpicId    string    `firestore:"epicId" json:"epicId" yaml:"epicId"`
	Content   string    `firestore:"content" json:"content" yaml:"content"`
	StartedAt time.Time `firestore:"startedAt" json:"startedAt" yaml:"startedAt"`
	EndedAt   time.Time `firestore:"endedAt" json:"endedAt" yaml:"endedAt"`
	UserId    string    `firestore:"userId" json:"userId" yaml:"userId"`
	UserName  string    `firestore:"userName" json:"userName" yaml:"userName"`
	UserIcon  string    `firestore:"userIcon" json:"userIcon" yaml:"userIcon"`
	CreatedAt time.Time `firestore:"createdAt" json:"createdAt" yaml:"createdAt"`
	UpdatedAt time.Time `firestore:"updatedAt" json:"updatedAt" yaml:"updatedAt"`
}

func (a *Activity) GetProjectId() string {
	if a == nil {
		return ""
	}
	return a.ProjectId
}

func (a *Activity) GetEpicId() string {
	if a == nil {
		return ""
	}
	return a.EpicId
}

func (a *Activity) GetContent() string {
	if a == nil {
		return ""
	}
	return a.Content
}

func (a *Activity) GetStartedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.StartedAt
}

func (a *Activity) GetEndedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.EndedAt
}

func (a *Activity) GetUserId() string {
	if a == nil {
		return ""
	}
	return a.UserId
}

func (a *Activity) GetUserName() string {
	if a == nil {
		return ""
	}
	return a.UserName
}

func (a *Activity) GetUserIcon() string {
	if a == nil {
		return ""
	}
	return a.UserIcon
}

func (a *Activity) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *Activity) GetUpdatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.UpdatedAt
}

func (a *Activity) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

// ActivityFields contains field names for Activity.
var ActivityFields = struct {
	Id        string
	ProjectId string
	EpicId    string
	Content   string
	StartedAt string
	EndedAt   string
	UserId    string
	UserName  string
	UserIcon  string
	CreatedAt string
	UpdatedAt string
}{
	Id:        "id",
	ProjectId: "projectId",
	EpicId:    "epicId",
	Content:   "content",
	StartedAt: "startedAt",
	EndedAt:   "endedAt",
	UserId:    "userId",
	UserName:  "userName",
	UserIcon:  "userIcon",
	CreatedAt: "createdAt",
	UpdatedAt: "updatedAt",
}
