// Code generated by youdoyou-firestore-kit. DO NOT EDIT.

package schema

import (
	"time"
)

// Collection names
const (
	CollectionAnalysisJobs = "analysisJobs"
)

// AnalysisJobPath returns the document path for a analysisJob.
func AnalysisJobPath(jobID string) string {
	return "analysis_jobs/" + jobID
}

type StepStatus string

const (
	StepStatusPENDING StepStatus = "PENDING"
	StepStatusDONE    StepStatus = "DONE"
)

type Step struct {
	Status      StepStatus `firestore:"status" json:"status" yaml:"status"`
	OutputRef   string     `firestore:"outputRef" json:"outputRef" yaml:"outputRef"`
	CompletedAt time.Time  `firestore:"completedAt" json:"completedAt" yaml:"completedAt"`
}

func (s *Step) GetStatus() StepStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *Step) GetOutputRef() string {
	if s == nil {
		return ""
	}
	return s.OutputRef
}

func (s *Step) GetCompletedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CompletedAt
}

type AnalysisJobStatus string

const (
	AnalysisJobStatusPENDING    AnalysisJobStatus = "PENDING"
	AnalysisJobStatusPROCESSING AnalysisJobStatus = "PROCESSING"
	AnalysisJobStatusCOMPLETED  AnalysisJobStatus = "COMPLETED"
	AnalysisJobStatusFAILED     AnalysisJobStatus = "FAILED"
)

type AnalysisJob struct {
	ID        string            `firestore:"-" json:"id" yaml:"id"`
	UserId    string            `firestore:"userId" json:"userId" yaml:"userId"`
	Status    AnalysisJobStatus `firestore:"status" json:"status" yaml:"status"`
	Steps     map[string]*Step  `firestore:"steps" json:"steps" yaml:"steps"`
	CreatedAt time.Time         `firestore:"createdAt" json:"createdAt" yaml:"createdAt"`
	UpdatedAt time.Time         `firestore:"updatedAt" json:"updatedAt" yaml:"updatedAt"`
}

func (a *AnalysisJob) GetUserId() string {
	if a == nil {
		return ""
	}
	return a.UserId
}

func (a *AnalysisJob) GetStatus() AnalysisJobStatus {
	if a == nil {
		return ""
	}
	return a.Status
}

func (a *AnalysisJob) GetSteps() map[string]*Step {
	if a == nil {
		return nil
	}
	return a.Steps
}

func (a *AnalysisJob) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *AnalysisJob) GetUpdatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.UpdatedAt
}

func (a *AnalysisJob) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

// StepFields contains field names for Step.
var StepFields = struct {
	Status      string
	OutputRef   string
	CompletedAt string
}{
	Status:      "status",
	OutputRef:   "outputRef",
	CompletedAt: "completedAt",
}

// AnalysisJobFields contains field names for AnalysisJob.
var AnalysisJobFields = struct {
	Id        string
	UserId    string
	Status    string
	Steps     string
	CreatedAt string
	UpdatedAt string
}{
	Id:        "id",
	UserId:    "userId",
	Status:    "status",
	Steps:     "steps",
	CreatedAt: "createdAt",
	UpdatedAt: "updatedAt",
}
