// Code generated by youdoyou-firestore-kit. DO NOT EDIT.

package schema

import (
	"time"
)

// Collection names
const (
	CollectionProjects = "projects"
)

// ProjectPath returns the document path for a project.
func ProjectPath(projectID string) string {
	return "projects/" + projectID
}

type Epic struct {
	Id       string `firestore:"id" json:"id" yaml:"id"`
	Title    string `firestore:"title" json:"title" yaml:"title"`
	ImageUrl string `firestore:"imageUrl" json:"imageUrl" yaml:"imageUrl"`
}

func (e *Epic) GetId() string {
	if e == nil {
		return ""
	}
	return e.Id
}

func (e *Epic) GetTitle() string {
	if e == nil {
		return ""
	}
	return e.Title
}

func (e *Epic) GetImageUrl() string {
	if e == nil {
		return ""
	}
	return e.ImageUrl
}

type Project struct {
	ID          string    `firestore:"-" json:"id" yaml:"id"`
	Title       string    `firestore:"title" json:"title" yaml:"title"`
	Description string    `firestore:"description" json:"description" yaml:"description"`
	Epics       []*Epic   `firestore:"epics" json:"epics" yaml:"epics"`
	IconUrl     string    `firestore:"iconUrl" json:"iconUrl" yaml:"iconUrl"`
	CreatedAt   time.Time `firestore:"createdAt" json:"createdAt" yaml:"createdAt"`
	UpdatedAt   time.Time `firestore:"updatedAt" json:"updatedAt" yaml:"updatedAt"`
}

func (p *Project) GetTitle() string {
	if p == nil {
		return ""
	}
	return p.Title
}

func (p *Project) GetDescription() string {
	if p == nil {
		return ""
	}
	return p.Description
}

func (p *Project) GetEpics() []*Epic {
	if p == nil {
		return nil
	}
	return p.Epics
}

func (p *Project) GetIconUrl() string {
	if p == nil {
		return ""
	}
	return p.IconUrl
}

func (p *Project) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *Project) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *Project) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

// EpicFields contains field names for Epic.
var EpicFields = struct {
	Id       string
	Title    string
	ImageUrl string
}{
	Id:       "id",
	Title:    "title",
	ImageUrl: "imageUrl",
}

// ProjectFields contains field names for Project.
var ProjectFields = struct {
	Id          string
	Title       string
	Description string
	Epics       string
	IconUrl     string
	CreatedAt   string
	UpdatedAt   string
}{
	Id:          "id",
	Title:       "title",
	Description: "description",
	Epics:       "epics",
	IconUrl:     "iconUrl",
	CreatedAt:   "createdAt",
	UpdatedAt:   "updatedAt",
}
